services:
  web:
    container_name: "algotn-website"
    build: .
    restart: always
    environment:
      REDIS_HOST: "redis"
      API_SECRET_TOKEN: "secret_token"
    depends_on:
      - redis
    ports:
      - "8080:8080"
    volumes:
      - ./config.yml:/config.yml
  redis:
    image: "redis:latest"
    command: redis-server --port 6379
    restart: always
    ports:
      - "6379:6379"