services:
  web:
    container_name: "algotn-website"
    image: "ghcr.io/tn-club-algo/website:main"
    restart: always
    environment:
      API_SECRET_TOKEN: "secret_token"
      WEBSOCKET_SECRET_TOKEN: "secret_token"
      REDIS_ADDRESS: "redis://redis"
      REDIS_PORT: "6379"
      REDIS_PASS: ""
      REDIS_DATABASE: "0"
      CLOUDFLARE_SECRET: "cf_turnstile_secret"
    depends_on:
      - redis
    ports:
      - "8080:8080"
    volumes:
      - ./config.yml:/config.yml
  pepper:
    container_name: "pepper"
    image: "ghcr.io/tn-club-algo/pepper:main"
    restart: always
    environment:
      MAX_RAM: "16384"
      WEBSITE_URL: "localhost"
      API_SECRET: "secret_token"
      REDIS_ADDRESS_PORT: "redis:6379"
      REDIS_PASS: ""
    depends_on:
      - redis
  redis:
    image: "redis:latest"
    command: redis-server --port 6379
    restart: always
    ports:
      - "6379:6379"