services:
  web:
    container_name: "AlgoTN Website"
    build: .
    restart: always
    environment:
      API_SECRET_TOKEN: "secret_token"
    depends_on:
      - redis
    ports:
      - "8080:8080"
  pepper:
    container_name: "Pepper"
    image: "pepper"
    restart: always
    environment:
      # Same as the web service
      API_SECRET_TOKEN: "secret_token"
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    restart: always